import { Component, OnInit } from '@angular/core';
import { KeyValue } from '../../classes/key-value';

@Component({
  selector: 'app-identificacion-paciente',
  templateUrl: './identificacion-paciente.component.html',
  styleUrls: ['./identificacion-paciente.component.css']
})
export class IdentificacionPacienteComponent implements OnInit {

  myAwesomeArrayOfAwesomeStuff : Array<KeyValue> = [{ key : '05001', value : 'MEDELLIN (ANTIOQUIA)'},
  { key : '05002', value : 'ABEJORRAL (ANTIOQUIA)'},
  { key : '05004', value : 'ABRIAQUI (ANTIOQUIA)'},
  { key : '05021', value : 'ALEJANDRIA (ANTIOQUIA)'},
  { key : '05030', value : 'AMAGA (ANTIOQUIA)'},
  { key : '05031', value : 'AMALFI (ANTIOQUIA)'},
  { key : '05034', value : 'ANDES (ANTIOQUIA)'},
  { key : '05036', value : 'ANGELOPOLIS (ANTIOQUIA)'},
  { key : '05038', value : 'ANGOSTURA (ANTIOQUIA)'},
  { key : '05040', value : 'ANORI (ANTIOQUIA)'},
  { key : '05042', value : 'SANTAFE DE ANTIOQUIA (ANTIOQUIA)'},
  { key : '05044', value : 'ANZA (ANTIOQUIA)'},
  { key : '05045', value : 'APARTADO (ANTIOQUIA)'},
  { key : '05051', value : 'ARBOLETES (ANTIOQUIA)'},
  { key : '05055', value : 'ARGELIA (ANTIOQUIA)'},
  { key : '05059', value : 'ARMENIA (ANTIOQUIA)'},
  { key : '05079', value : 'BARBOSA (ANTIOQUIA)'},
  { key : '05086', value : 'BELMIRA (ANTIOQUIA)'},
  { key : '05088', value : 'BELLO (ANTIOQUIA)'},
  { key : '05091', value : 'BETANIA (ANTIOQUIA)'},
  { key : '05093', value : 'BETULIA (ANTIOQUIA)'},
  { key : '05101', value : 'CIUDAD BOLIVAR (ANTIOQUIA)'},
  { key : '05107', value : 'BRICEÑO (ANTIOQUIA)'},
  { key : '05113', value : 'BURITICA (ANTIOQUIA)'},
  { key : '05120', value : 'CACERES (ANTIOQUIA)'},
  { key : '05125', value : 'CAICEDO (ANTIOQUIA)'},
  { key : '05129', value : 'CALDAS (ANTIOQUIA)'},
  { key : '05134', value : 'CAMPAMENTO (ANTIOQUIA)'},
  { key : '05138', value : 'CAÑASGORDAS (ANTIOQUIA)'},
  { key : '05142', value : 'CARACOLI (ANTIOQUIA)'},
  { key : '05145', value : 'CARAMANTA (ANTIOQUIA)'},
  { key : '05147', value : 'CAREPA (ANTIOQUIA)'},
  { key : '05148', value : 'EL CARMEN DE VIBORAL (ANTIOQUIA)'},
  { key : '05150', value : 'CAROLINA (ANTIOQUIA)'},
  { key : '05154', value : 'CAUCASIA (ANTIOQUIA)'},
  { key : '05172', value : 'CHIGORODO (ANTIOQUIA)'},
  { key : '05190', value : 'CISNEROS (ANTIOQUIA)'},
  { key : '05197', value : 'COCORNA (ANTIOQUIA)'},
  { key : '05206', value : 'CONCEPCION (ANTIOQUIA)'},
  { key : '05209', value : 'CONCORDIA (ANTIOQUIA)'},
  { key : '05212', value : 'COPACABANA (ANTIOQUIA)'},
  { key : '05234', value : 'DABEIBA (ANTIOQUIA)'},
  { key : '05237', value : 'DON MATIAS (ANTIOQUIA)'},
  { key : '05240', value : 'EBEJICO (ANTIOQUIA)'},
  { key : '05250', value : 'EL BAGRE (ANTIOQUIA)'},
  { key : '05264', value : 'ENTRERRIOS (ANTIOQUIA)'},
  { key : '05266', value : 'ENVIGADO (ANTIOQUIA)'},
  { key : '05282', value : 'FREDONIA (ANTIOQUIA)'},
  { key : '05284', value : 'FRONTINO (ANTIOQUIA)'},
  { key : '05306', value : 'GIRALDO (ANTIOQUIA)'},
  { key : '05308', value : 'GIRARDOTA (ANTIOQUIA)'},
  { key : '05310', value : 'GOMEZ PLATA (ANTIOQUIA)'},
  { key : '05313', value : 'GRANADA (ANTIOQUIA)'},
  { key : '05315', value : 'GUADALUPE (ANTIOQUIA)'},
  { key : '05318', value : 'GUARNE (ANTIOQUIA)'},
  { key : '05321', value : 'GUATAPE (ANTIOQUIA)'},
  { key : '05347', value : 'HELICONIA (ANTIOQUIA)'},
  { key : '05353', value : 'HISPANIA (ANTIOQUIA)'},
  { key : '05360', value : 'ITAGUI (ANTIOQUIA)'},
  { key : '05361', value : 'ITUANGO (ANTIOQUIA)'},
  { key : '05364', value : 'JARDIN (ANTIOQUIA)'},
  { key : '05368', value : 'JERICO (ANTIOQUIA)'},
  { key : '05376', value : 'LA CEJA (ANTIOQUIA)'},
  { key : '05380', value : 'LA ESTRELLA (ANTIOQUIA)'},
  { key : '05390', value : 'LA PINTADA (ANTIOQUIA)'},
  { key : '05400', value : 'LA UNION (ANTIOQUIA)'},
  { key : '05411', value : 'LIBORINA (ANTIOQUIA)'},
  { key : '05425', value : 'MACEO (ANTIOQUIA)'},
  { key : '05440', value : 'MARINILLA (ANTIOQUIA)'},
  { key : '05467', value : 'MONTEBELLO (ANTIOQUIA)'},
  { key : '05475', value : 'MURINDO (ANTIOQUIA)'},
  { key : '05480', value : 'MUTATA (ANTIOQUIA)'},
  { key : '05483', value : 'NARIÑO (ANTIOQUIA)'},
  { key : '05490', value : 'NECOCLI (ANTIOQUIA)'},
  { key : '05495', value : 'NECHI (ANTIOQUIA)'},
  { key : '05501', value : 'OLAYA (ANTIOQUIA)'},
  { key : '05541', value : 'PEÐOL (ANTIOQUIA)'},
  { key : '05543', value : 'PEQUE (ANTIOQUIA)'},
  { key : '05576', value : 'PUEBLORRICO (ANTIOQUIA)'},
  { key : '05579', value : 'PUERTO BERRIO (ANTIOQUIA)'},
  { key : '05585', value : 'PUERTO NARE (ANTIOQUIA)'},
  { key : '05591', value : 'PUERTO TRIUNFO (ANTIOQUIA)'},
  { key : '05604', value : 'REMEDIOS (ANTIOQUIA)'},
  { key : '05607', value : 'RETIRO (ANTIOQUIA)'},
  { key : '05615', value : 'RIONEGRO (ANTIOQUIA)'},
  { key : '05628', value : 'SABANALARGA (ANTIOQUIA)'},
  { key : '05631', value : 'SABANETA (ANTIOQUIA)'},
  { key : '05642', value : 'SALGAR (ANTIOQUIA)'},
  { key : '05647', value : 'SAN ANDRES DE CUERQUIA (ANTIOQUIA)'},
  { key : '05649', value : 'SAN CARLOS (ANTIOQUIA)'},
  { key : '05652', value : 'SAN FRANCISCO (ANTIOQUIA)'},
  { key : '05656', value : 'SAN JERONIMO (ANTIOQUIA)'},
  { key : '05658', value : 'SAN JOSE DE LA MONTAÑA (ANTIOQUIA)'},
  { key : '05659', value : 'SAN JUAN DE URABA (ANTIOQUIA)'},
  { key : '05660', value : 'SAN LUIS (ANTIOQUIA)'},
  { key : '05664', value : 'SAN PEDRO (ANTIOQUIA)'},
  { key : '05665', value : 'SAN PEDRO DE URABA (ANTIOQUIA)'},
  { key : '05667', value : 'SAN RAFAEL (ANTIOQUIA)'},
  { key : '05670', value : 'SAN ROQUE (ANTIOQUIA)'},
  { key : '05674', value : 'SAN VICENTE (ANTIOQUIA)'},
  { key : '05679', value : 'SANTA BARBARA (ANTIOQUIA)'},
  { key : '05686', value : 'SANTA ROSA DE OSOS (ANTIOQUIA)'},
  { key : '05690', value : 'SANTO DOMINGO (ANTIOQUIA)'},
  { key : '05697', value : 'EL SANTUARIO (ANTIOQUIA)'},
  { key : '05736', value : 'SEGOVIA (ANTIOQUIA)'},
  { key : '05756', value : 'SONSON (ANTIOQUIA)'},
  { key : '05761', value : 'SOPETRAN (ANTIOQUIA)'},
  { key : '05789', value : 'TAMESIS (ANTIOQUIA)'},
  { key : '05790', value : 'TARAZA (ANTIOQUIA)'},
  { key : '05792', value : 'TARSO (ANTIOQUIA)'},
  { key : '05809', value : 'TITIRIBI (ANTIOQUIA)'},
  { key : '05819', value : 'TOLEDO (ANTIOQUIA)'},
  { key : '05837', value : 'TURBO (ANTIOQUIA)'},
  { key : '05842', value : 'URAMITA (ANTIOQUIA)'},
  { key : '05847', value : 'URRAO (ANTIOQUIA)'},
  { key : '05854', value : 'VALDIVIA (ANTIOQUIA)'},
  { key : '05856', value : 'VALPARAISO (ANTIOQUIA)'},
  { key : '05858', value : 'VEGACHI (ANTIOQUIA)'},
  { key : '05861', value : 'VENECIA (ANTIOQUIA)'},
  { key : '05873', value : 'VIGIA DEL FUERTE (ANTIOQUIA)'},
  { key : '05885', value : 'YALI (ANTIOQUIA)'},
  { key : '05887', value : 'YARUMAL (ANTIOQUIA)'},
  { key : '05890', value : 'YOLOMBO (ANTIOQUIA)'},
  { key : '05893', value : 'YONDO (ANTIOQUIA)'},
  { key : '05895', value : 'ZARAGOZA (ANTIOQUIA)'},
  { key : '08001', value : 'BARRANQUILLA (ATLANTICO)'},
  { key : '08078', value : 'BARANOA (ATLANTICO)'},
  { key : '08137', value : 'CAMPO DE LA CRUZ (ATLANTICO)'},
  { key : '08141', value : 'CANDELARIA (ATLANTICO)'},
  { key : '08296', value : 'GALAPA (ATLANTICO)'},
  { key : '08372', value : 'JUAN DE ACOSTA (ATLANTICO)'},
  { key : '08421', value : 'LURUACO (ATLANTICO)'},
  { key : '08433', value : 'MALAMBO (ATLANTICO)'},
  { key : '08436', value : 'MANATI (ATLANTICO)'},
  { key : '08520', value : 'PALMAR DE VARELA (ATLANTICO)'},
  { key : '08549', value : 'PIOJO (ATLANTICO)'},
  { key : '08558', value : 'POLONUEVO (ATLANTICO)'},
  { key : '08560', value : 'PONEDERA (ATLANTICO)'},
  { key : '08573', value : 'PUERTO COLOMBIA (ATLANTICO)'},
  { key : '08606', value : 'REPELON (ATLANTICO)'},
  { key : '08634', value : 'SABANAGRANDE (ATLANTICO)'},
  { key : '08638', value : 'SABANALARGA (ATLANTICO)'},
  { key : '08675', value : 'SANTA LUCIA (ATLANTICO)'},
  { key : '08685', value : 'SANTO TOMAS (ATLANTICO)'},
  { key : '08758', value : 'SOLEDAD (ATLANTICO)'},
  { key : '08770', value : 'SUAN (ATLANTICO)'},
  { key : '08832', value : 'TUBARA (ATLANTICO)'},
  { key : '08849', value : 'USIACURI (ATLANTICO)'},
  { key : '11001', value : 'BOGOTA, D.C. (BOGOTA)'},
  { key : '13001', value : 'CARTAGENA (BOLIVAR)'},
  { key : '13006', value : 'ACHI (BOLIVAR)'},
  { key : '13030', value : 'ALTOS DEL ROSARIO (BOLIVAR)'},
  { key : '13042', value : 'ARENAL (BOLIVAR)'},
  { key : '13052', value : 'ARJONA (BOLIVAR)'},
  { key : '13062', value : 'ARROYOHONDO (BOLIVAR)'},
  { key : '13074', value : 'BARRANCO DE LOBA (BOLIVAR)'},
  { key : '13140', value : 'CALAMAR (BOLIVAR)'},
  { key : '13160', value : 'CANTAGALLO (BOLIVAR)'},
  { key : '13188', value : 'CICUCO (BOLIVAR)'},
  { key : '13212', value : 'CORDOBA (BOLIVAR)'},
  { key : '13222', value : 'CLEMENCIA (BOLIVAR)'},
  { key : '13244', value : 'EL CARMEN DE BOLIVAR (BOLIVAR)'},
  { key : '13248', value : 'EL GUAMO (BOLIVAR)'},
  { key : '13268', value : 'EL PEÑON (BOLIVAR)'},
  { key : '13300', value : 'HATILLO DE LOBA (BOLIVAR)'},
  { key : '13430', value : 'MAGANGUE (BOLIVAR)'},
  { key : '13433', value : 'MAHATES (BOLIVAR)'},
  { key : '13440', value : 'MARGARITA (BOLIVAR)'},
  { key : '13442', value : 'MARIA LA BAJA (BOLIVAR)'},
  { key : '13458', value : 'MONTECRISTO (BOLIVAR)'},
  { key : '13468', value : 'MOMPOS (BOLIVAR)'},
  { key : '13490', value : 'NOROSI (BOLIVAR)'},
  { key : '13473', value : 'MORALES (BOLIVAR)'},
  { key : '13549', value : 'PINILLOS (BOLIVAR)'},
  { key : '13580', value : 'REGIDOR (BOLIVAR)'},
  { key : '13600', value : 'RIO VIEJO (BOLIVAR)'},
  { key : '13620', value : 'SAN CRISTOBAL (BOLIVAR)'},
  { key : '13647', value : 'SAN ESTANISLAO (BOLIVAR)'},
  { key : '13650', value : 'SAN FERNANDO (BOLIVAR)'},
  { key : '13654', value : 'SAN JACINTO (BOLIVAR)'},
  { key : '13655', value : 'SAN JACINTO DEL CAUCA (BOLIVAR)'},
  { key : '13657', value : 'SAN JUAN NEPOMUCENO (BOLIVAR)'},
  { key : '13667', value : 'SAN MARTIN DE LOBA (BOLIVAR)'},
  { key : '13670', value : 'SAN PABLO (BOLIVAR)'},
  { key : '13673', value : 'SANTA CATALINA (BOLIVAR)'},
  { key : '13683', value : 'SANTA ROSA (BOLIVAR)'},
  { key : '13688', value : 'SANTA ROSA DEL SUR (BOLIVAR)'},
  { key : '13744', value : 'SIMITI (BOLIVAR)'},
  { key : '13760', value : 'SOPLAVIENTO (BOLIVAR)'},
  { key : '13780', value : 'TALAIGUA NUEVO (BOLIVAR)'},
  { key : '13810', value : 'TIQUISIO (BOLIVAR)'},
  { key : '13836', value : 'TURBACO (BOLIVAR)'},
  { key : '13838', value : 'TURBANA (BOLIVAR)'},
  { key : '13873', value : 'VILLANUEVA (BOLIVAR)'},
  { key : '13894', value : 'ZAMBRANO (BOLIVAR)'},
  { key : '15001', value : 'TUNJA (BOYACA)'},
  { key : '15022', value : 'ALMEIDA (BOYACA)'},
  { key : '15047', value : 'AQUITANIA (BOYACA)'},
  { key : '15051', value : 'ARCABUCO (BOYACA)'},
  { key : '15087', value : 'BELEN (BOYACA)'},
  { key : '15090', value : 'BERBEO (BOYACA)'},
  { key : '15092', value : 'BETEITIVA (BOYACA)'},
  { key : '15097', value : 'BOAVITA (BOYACA)'},
  { key : '15104', value : 'BOYACA (BOYACA)'},
  { key : '15106', value : 'BRICEÑO (BOYACA)'},
  { key : '15109', value : 'BUENAVISTA (BOYACA)'},
  { key : '15114', value : 'BUSBANZA (BOYACA)'},
  { key : '15131', value : 'CALDAS (BOYACA)'},
  { key : '15135', value : 'CAMPOHERMOSO (BOYACA)'},
  { key : '15162', value : 'CERINZA (BOYACA)'},
  { key : '15172', value : 'CHINAVITA (BOYACA)'},
  { key : '15176', value : 'CHIQUINQUIRA (BOYACA)'},
  { key : '15180', value : 'CHISCAS (BOYACA)'},
  { key : '15183', value : 'CHITA (BOYACA)'},
  { key : '15185', value : 'CHITARAQUE (BOYACA)'},
  { key : '15187', value : 'CHIVATA (BOYACA)'},
  { key : '15189', value : 'CIENEGA (BOYACA)'},
  { key : '15204', value : 'COMBITA (BOYACA)'},
  { key : '15212', value : 'COPER (BOYACA)'},
  { key : '15215', value : 'CORRALES (BOYACA)'},
  { key : '15218', value : 'COVARACHIA (BOYACA)'},
  { key : '15223', value : 'CUBARA (BOYACA)'},
  { key : '15224', value : 'CUCAITA (BOYACA)'},
  { key : '15226', value : 'CUITIVA (BOYACA)'},
  { key : '15232', value : 'CHIQUIZA (BOYACA)'},
  { key : '15236', value : 'CHIVOR (BOYACA)'},
  { key : '15238', value : 'DUITAMA (BOYACA)'},
  { key : '15244', value : 'EL COCUY (BOYACA)'},
  { key : '15248', value : 'EL ESPINO (BOYACA)'},
  { key : '15272', value : 'FIRAVITOBA (BOYACA)'},
  { key : '15276', value : 'FLORESTA (BOYACA)'},
  { key : '15293', value : 'GACHANTIVA (BOYACA)'},
  { key : '15296', value : 'GAMEZA (BOYACA)'},
  { key : '15299', value : 'GARAGOA (BOYACA)'},
  { key : '15317', value : 'GUACAMAYAS (BOYACA)'},
  { key : '15322', value : 'GUATEQUE (BOYACA)'},
  { key : '15325', value : 'GUAYATA (BOYACA)'},
  { key : '15332', value : 'GsICAN (BOYACA)'},
  { key : '15362', value : 'IZA (BOYACA)'},
  { key : '15367', value : 'JENESANO (BOYACA)'},
  { key : '15368', value : 'JERICO (BOYACA)'},
  { key : '15377', value : 'LABRANZAGRANDE (BOYACA)'},
  { key : '15380', value : 'LA CAPILLA (BOYACA)'},
  { key : '15401', value : 'LA VICTORIA (BOYACA)'},
  { key : '15403', value : 'LA UVITA (BOYACA)'},
  { key : '15407', value : 'VILLA DE LEYVA (BOYACA)'},
  { key : '15425', value : 'MACANAL (BOYACA)'},
  { key : '15442', value : 'MARIPI (BOYACA)'},
  { key : '15455', value : 'MIRAFLORES (BOYACA)'},
  { key : '15464', value : 'MONGUA (BOYACA)'},
  { key : '15466', value : 'MONGUI (BOYACA)'},
  { key : '15469', value : 'MONIQUIRA (BOYACA)'},
  { key : '15476', value : 'MOTAVITA (BOYACA)'},
  { key : '15480', value : 'MUZO (BOYACA)'},
  { key : '15491', value : 'NOBSA (BOYACA)'},
  { key : '15494', value : 'NUEVO COLON (BOYACA)'},
  { key : '15500', value : 'OICATA (BOYACA)'},
  { key : '15507', value : 'OTANCHE (BOYACA)'},
  { key : '15511', value : 'PACHAVITA (BOYACA)'},
  { key : '15514', value : 'PAEZ (BOYACA)'},
  { key : '15516', value : 'PAIPA (BOYACA)'},
  { key : '15518', value : 'PAJARITO (BOYACA)'},
  { key : '15522', value : 'PANQUEBA (BOYACA)'},
  { key : '15531', value : 'PAUNA (BOYACA)'},
  { key : '15533', value : 'PAYA (BOYACA)'},
  { key : '15537', value : 'PAZ DE RIO (BOYACA)'},
  { key : '15542', value : 'PESCA (BOYACA)'},
  { key : '15550', value : 'PISBA (BOYACA)'},
  { key : '15572', value : 'PUERTO BOYACA (BOYACA)'},
  { key : '15580', value : 'QUIPAMA (BOYACA)'},
  { key : '15599', value : 'RAMIRIQUI (BOYACA)'},
  { key : '15600', value : 'RAQUIRA (BOYACA)'},
  { key : '15621', value : 'RONDON (BOYACA)'},
  { key : '15632', value : 'SABOYA (BOYACA)'},
  { key : '15638', value : 'SACHICA (BOYACA)'},
  { key : '15646', value : 'SAMACA (BOYACA)'},
  { key : '15660', value : 'SAN EDUARDO (BOYACA)'},
  { key : '15664', value : 'SAN JOSE DE PARE (BOYACA)'},
  { key : '15667', value : 'SAN LUIS DE GACENO (BOYACA)'},
  { key : '15673', value : 'SAN MATEO (BOYACA)'},
  { key : '15676', value : 'SAN MIGUEL DE SEMA (BOYACA)'},
  { key : '15681', value : 'SAN PABLO DE BORBUR (BOYACA)'},
  { key : '15686', value : 'SANTANA (BOYACA)'},
  { key : '15690', value : 'SANTA MARIA (BOYACA)'},
  { key : '15693', value : 'SANTA ROSA DE VITERBO (BOYACA)'},
  { key : '15696', value : 'SANTA SOFIA (BOYACA)'},
  { key : '15720', value : 'SATIVANORTE (BOYACA)'},
  { key : '15723', value : 'SATIVASUR (BOYACA)'},
  { key : '15740', value : 'SIACHOQUE (BOYACA)'},
  { key : '15753', value : 'SOATA (BOYACA)'},
  { key : '15755', value : 'SOCOTA (BOYACA)'},
  { key : '15757', value : 'SOCHA (BOYACA)'},
  { key : '15759', value : 'SOGAMOSO (BOYACA)'},
  { key : '15761', value : 'SOMONDOCO (BOYACA)'},
  { key : '15762', value : 'SORA (BOYACA)'},
  { key : '15763', value : 'SOTAQUIRA (BOYACA)'},
  { key : '15764', value : 'SORACA (BOYACA)'},
  { key : '15774', value : 'SUSACON (BOYACA)'},
  { key : '15776', value : 'SUTAMARCHAN (BOYACA)'},
  { key : '15778', value : 'SUTATENZA (BOYACA)'},
  { key : '15790', value : 'TASCO (BOYACA)'},
  { key : '15798', value : 'TENZA (BOYACA)'},
  { key : '15804', value : 'TIBANA (BOYACA)'},
  { key : '15806', value : 'TIBASOSA (BOYACA)'},
  { key : '15808', value : 'TINJACA (BOYACA)'},
  { key : '15810', value : 'TIPACOQUE (BOYACA)'},
  { key : '15814', value : 'TOCA (BOYACA)'},
  { key : '15816', value : 'TOGsI (BOYACA)'},
  { key : '15820', value : 'TOPAGA (BOYACA)'},
  { key : '15822', value : 'TOTA (BOYACA)'},
  { key : '15832', value : 'TUNUNGUA (BOYACA)'},
  { key : '15835', value : 'TURMEQUE (BOYACA)'},
  { key : '15837', value : 'TUTA (BOYACA)'},
  { key : '15839', value : 'TUTAZA (BOYACA)'},
  { key : '15842', value : 'UMBITA (BOYACA)'},
  { key : '15861', value : 'VENTAQUEMADA (BOYACA)'},
  { key : '15879', value : 'VIRACACHA (BOYACA)'},
  { key : '15897', value : 'ZETAQUIRA (BOYACA)'},
  { key : '17001', value : 'MANIZALES (CALDAS)'},
  { key : '17013', value : 'AGUADAS (CALDAS)'},
  { key : '17042', value : 'ANSERMA (CALDAS)'},
  { key : '17050', value : 'ARANZAZU (CALDAS)'},
  { key : '17088', value : 'BELALCAZAR (CALDAS)'},
  { key : '17174', value : 'CHINCHINA (CALDAS)'},
  { key : '17272', value : 'FILADELFIA (CALDAS)'},
  { key : '17380', value : 'LA DORADA (CALDAS)'},
  { key : '17388', value : 'LA MERCED (CALDAS)'},
  { key : '17433', value : 'MANZANARES (CALDAS)'},
  { key : '17442', value : 'MARMATO (CALDAS)'},
  { key : '17444', value : 'MARQUETALIA (CALDAS)'},
  { key : '17446', value : 'MARULANDA (CALDAS)'},
  { key : '17486', value : 'NEIRA (CALDAS)'},
  { key : '17495', value : 'NORCASIA (CALDAS)'},
  { key : '17513', value : 'PACORA (CALDAS)'},
  { key : '17524', value : 'PALESTINA (CALDAS)'},
  { key : '17541', value : 'PENSILVANIA (CALDAS)'},
  { key : '17614', value : 'RIOSUCIO (CALDAS)'},
  { key : '17616', value : 'RISARALDA (CALDAS)'},
  { key : '17653', value : 'SALAMINA (CALDAS)'},
  { key : '17662', value : 'SAMANA (CALDAS)'},
  { key : '17665', value : 'SAN JOSE (CALDAS)'},
  { key : '17777', value : 'SUPIA (CALDAS)'},
  { key : '17867', value : 'VICTORIA (CALDAS)'},
  { key : '17873', value : 'VILLAMARIA (CALDAS)'},
  { key : '17877', value : 'VITERBO (CALDAS)'},
  { key : '18001', value : 'FLORENCIA (CAQUETA)'},
  { key : '18029', value : 'ALBANIA (CAQUETA)'},
  { key : '18094', value : 'BELEN DE LOS ANDAQUIES (CAQUETA)'},
  { key : '18150', value : 'CARTAGENA DEL CHAIRA (CAQUETA)'},
  { key : '18205', value : 'CURILLO (CAQUETA)'},
  { key : '18247', value : 'EL DONCELLO (CAQUETA)'},
  { key : '18256', value : 'EL PAUJIL (CAQUETA)'},
  { key : '18410', value : 'LA MONTAÑITA (CAQUETA)'},
  { key : '18460', value : 'MILAN (CAQUETA)'},
  { key : '18479', value : 'MORELIA (CAQUETA)'},
  { key : '18592', value : 'PUERTO RICO (CAQUETA)'},
  { key : '18610', value : 'SAN JOSE DEL FRAGUA (CAQUETA)'},
  { key : '18753', value : 'SAN VICENTE DEL CAGUAN (CAQUETA)'},
  { key : '18756', value : 'SOLANO (CAQUETA)'},
  { key : '18785', value : 'SOLITA (CAQUETA)'},
  { key : '18860', value : 'VALPARAISO (CAQUETA)'},
  { key : '19001', value : 'POPAYAN (CAUCA)'},
  { key : '19022', value : 'ALMAGUER (CAUCA)'},
  { key : '19050', value : 'ARGELIA (CAUCA)'},
  { key : '19075', value : 'BALBOA (CAUCA)'},
  { key : '19100', value : 'BOLIVAR (CAUCA)'},
  { key : '19110', value : 'BUENOS AIRES (CAUCA)'},
  { key : '19130', value : 'CAJIBIO (CAUCA)'},
  { key : '19137', value : 'CALDONO (CAUCA)'},
  { key : '19142', value : 'CALOTO (CAUCA)'},
  { key : '19212', value : 'CORINTO (CAUCA)'},
  { key : '19256', value : 'EL TAMBO (CAUCA)'},
  { key : '19290', value : 'FLORENCIA (CAUCA)'},
  { key : '19300', value : 'GUACHENE (CAUCA)'},
  { key : '19318', value : 'GUAPI (CAUCA)'},
  { key : '19355', value : 'INZA (CAUCA)'},
  { key : '19364', value : 'JAMBALO (CAUCA)'},
  { key : '19392', value : 'LA SIERRA (CAUCA)'},
  { key : '19397', value : 'LA VEGA (CAUCA)'},
  { key : '19418', value : 'LOPEZ (CAUCA)'},
  { key : '19450', value : 'MERCADERES (CAUCA)'},
  { key : '19455', value : 'MIRANDA (CAUCA)'},
  { key : '19473', value : 'MORALES (CAUCA)'},
  { key : '19513', value : 'PADILLA (CAUCA)'},
  { key : '19517', value : 'PAEZ (CAUCA)'},
  { key : '19532', value : 'PATIA (CAUCA)'},
  { key : '19533', value : 'PIAMONTE (CAUCA)'},
  { key : '19548', value : 'PIENDAMO (CAUCA)'},
  { key : '19573', value : 'PUERTO TEJADA (CAUCA)'},
  { key : '19585', value : 'PURACE (CAUCA)'},
  { key : '19622', value : 'ROSAS (CAUCA)'},
  { key : '19693', value : 'SAN SEBASTIAN (CAUCA)'},
  { key : '19698', value : 'SANTANDER DE QUILICHAO (CAUCA)'},
  { key : '19701', value : 'SANTA ROSA (CAUCA)'},
  { key : '19743', value : 'SILVIA (CAUCA)'},
  { key : '19760', value : 'SOTARA (CAUCA)'},
  { key : '19780', value : 'SUAREZ (CAUCA)'},
  { key : '19785', value : 'SUCRE (CAUCA)'},
  { key : '19807', value : 'TIMBIO (CAUCA)'},
  { key : '19809', value : 'TIMBIQUI (CAUCA)'},
  { key : '19821', value : 'TORIBIO (CAUCA)'},
  { key : '19824', value : 'TOTORO (CAUCA)'},
  { key : '19845', value : 'VILLA RICA (CAUCA)'},
  { key : '20001', value : 'VALLEDUPAR (CESAR)'},
  { key : '20011', value : 'AGUACHICA (CESAR)'},
  { key : '20013', value : 'AGUSTIN CODAZZI (CESAR)'},
  { key : '20032', value : 'ASTREA (CESAR)'},
  { key : '20045', value : 'BECERRIL (CESAR)'},
  { key : '20060', value : 'BOSCONIA (CESAR)'},
  { key : '20175', value : 'CHIMICHAGUA (CESAR)'},
  { key : '20178', value : 'CHIRIGUANA (CESAR)'},
  { key : '20228', value : 'CURUMANI (CESAR)'},
  { key : '20238', value : 'EL COPEY (CESAR)'},
  { key : '20250', value : 'EL PASO (CESAR)'},
  { key : '20295', value : 'GAMARRA (CESAR)'},
  { key : '20310', value : 'GONZALEZ (CESAR)'},
  { key : '20383', value : 'LA GLORIA (CESAR)'},
  { key : '20400', value : 'LA JAGUA DE IBIRICO (CESAR)'},
  { key : '20443', value : 'MANAURE (CESAR)'},
  { key : '20517', value : 'PAILITAS (CESAR)'},
  { key : '20550', value : 'PELAYA (CESAR)'},
  { key : '20570', value : 'PUEBLO BELLO (CESAR)'},
  { key : '20614', value : 'RIO DE ORO (CESAR)'},
  { key : '20621', value : 'LA PAZ (CESAR)'},
  { key : '20710', value : 'SAN ALBERTO (CESAR)'},
  { key : '20750', value : 'SAN DIEGO (CESAR)'},
  { key : '20770', value : 'SAN MARTIN (CESAR)'},
  { key : '20787', value : 'TAMALAMEQUE (CESAR)'},
  { key : '23001', value : 'MONTERIA (CORDOBA)'},
  { key : '23068', value : 'AYAPEL (CORDOBA)'},
  { key : '23079', value : 'BUENAVISTA (CORDOBA)'},
  { key : '23090', value : 'CANALETE (CORDOBA)'},
  { key : '23162', value : 'CERETE (CORDOBA)'},
  { key : '23168', value : 'CHIMA (CORDOBA)'},
  { key : '23182', value : 'CHINU (CORDOBA)'},
  { key : '23189', value : 'CIENAGA DE ORO (CORDOBA)'},
  { key : '23300', value : 'COTORRA (CORDOBA)'},
  { key : '23350', value : 'LA APARTADA (CORDOBA)'},
  { key : '23417', value : 'LORICA (CORDOBA)'},
  { key : '23419', value : 'LOS CORDOBAS (CORDOBA)'},
  { key : '23464', value : 'MOMIL (CORDOBA)'},
  { key : '23466', value : 'MONTELIBANO (CORDOBA)'},
  { key : '23500', value : 'MOÑITOS (CORDOBA)'},
  { key : '23555', value : 'PLANETA RICA (CORDOBA)'},
  { key : '23570', value : 'PUEBLO NUEVO (CORDOBA)'},
  { key : '23574', value : 'PUERTO ESCONDIDO (CORDOBA)'},
  { key : '23580', value : 'PUERTO LIBERTADOR (CORDOBA)'},
  { key : '23586', value : 'PURISIMA (CORDOBA)'},
  { key : '23660', value : 'SAHAGUN (CORDOBA)'},
  { key : '23670', value : 'SAN ANDRES SOTAVENTO (CORDOBA)'},
  { key : '23672', value : 'SAN ANTERO (CORDOBA)'},
  { key : '23675', value : 'SAN BERNARDO DEL VIENTO (CORDOBA)'},
  { key : '23678', value : 'SAN CARLOS (CORDOBA)'},
  { key : '23686', value : 'SAN PELAYO (CORDOBA)'},
  { key : '23807', value : 'TIERRALTA (CORDOBA)'},
  { key : '23855', value : 'VALENCIA (CORDOBA)'},
  { key : '25001', value : 'AGUA DE DIOS (CUNDINAMARCA)'},
  { key : '25019', value : 'ALBAN (CUNDINAMARCA)'},
  { key : '25035', value : 'ANAPOIMA (CUNDINAMARCA)'},
  { key : '25040', value : 'ANOLAIMA (CUNDINAMARCA)'},
  { key : '25053', value : 'ARBELAEZ (CUNDINAMARCA)'},
  { key : '25086', value : 'BELTRAN (CUNDINAMARCA)'},
  { key : '25095', value : 'BITUIMA (CUNDINAMARCA)'},
  { key : '25099', value : 'BOJACA (CUNDINAMARCA)'},
  { key : '25120', value : 'CABRERA (CUNDINAMARCA)'},
  { key : '25123', value : 'CACHIPAY (CUNDINAMARCA)'},
  { key : '25126', value : 'CAJICA (CUNDINAMARCA)'},
  { key : '25148', value : 'CAPARRAPI (CUNDINAMARCA)'},
  { key : '25151', value : 'CAQUEZA (CUNDINAMARCA)'},
  { key : '25154', value : 'CARMEN DE CARUPA (CUNDINAMARCA)'},
  { key : '25168', value : 'CHAGUANI (CUNDINAMARCA)'},
  { key : '25175', value : 'CHIA (CUNDINAMARCA)'},
  { key : '25178', value : 'CHIPAQUE (CUNDINAMARCA)'},
  { key : '25181', value : 'CHOACHI (CUNDINAMARCA)'},
  { key : '25183', value : 'CHOCONTA (CUNDINAMARCA)'},
  { key : '25200', value : 'COGUA (CUNDINAMARCA)'},
  { key : '25214', value : 'COTA (CUNDINAMARCA)'},
  { key : '25224', value : 'CUCUNUBA (CUNDINAMARCA)'},
  { key : '25245', value : 'EL COLEGIO (CUNDINAMARCA)'},
  { key : '25258', value : 'EL PEÑON (CUNDINAMARCA)'},
  { key : '25260', value : 'EL ROSAL (CUNDINAMARCA)'},
  { key : '25269', value : 'FACATATIVA (CUNDINAMARCA)'},
  { key : '25279', value : 'FOMEQUE (CUNDINAMARCA)'},
  { key : '25281', value : 'FOSCA (CUNDINAMARCA)'},
  { key : '25286', value : 'FUNZA (CUNDINAMARCA)'},
  { key : '25288', value : 'FUQUENE (CUNDINAMARCA)'},
  { key : '25290', value : 'FUSAGASUGA (CUNDINAMARCA)'},
  { key : '25293', value : 'GACHALA (CUNDINAMARCA)'},
  { key : '25295', value : 'GACHANCIPA (CUNDINAMARCA)'},
  { key : '25297', value : 'GACHETA (CUNDINAMARCA)'},
  { key : '25299', value : 'GAMA (CUNDINAMARCA)'},
  { key : '25307', value : 'GIRARDOT (CUNDINAMARCA)'},
  { key : '25312', value : 'GRANADA (CUNDINAMARCA)'},
  { key : '25317', value : 'GUACHETA (CUNDINAMARCA)'},
  { key : '25320', value : 'GUADUAS (CUNDINAMARCA)'},
  { key : '25322', value : 'GUASCA (CUNDINAMARCA)'},
  { key : '25324', value : 'GUATAQUI (CUNDINAMARCA)'},
  { key : '25326', value : 'GUATAVITA (CUNDINAMARCA)'},
  { key : '25328', value : 'GUAYABAL DE SIQUIMA (CUNDINAMARCA)'},
  { key : '25335', value : 'GUAYABETAL (CUNDINAMARCA)'},
  { key : '25339', value : 'GUTIERREZ (CUNDINAMARCA)'},
  { key : '25368', value : 'JERUSALEN (CUNDINAMARCA)'},
  { key : '25372', value : 'JUNIN (CUNDINAMARCA)'},
  { key : '25377', value : 'LA CALERA (CUNDINAMARCA)'},
  { key : '25386', value : 'LA MESA (CUNDINAMARCA)'},
  { key : '25394', value : 'LA PALMA (CUNDINAMARCA)'},
  { key : '25398', value : 'LA PEÑA (CUNDINAMARCA)'},
  { key : '25402', value : 'LA VEGA (CUNDINAMARCA)'},
  { key : '25407', value : 'LENGUAZAQUE (CUNDINAMARCA)'},
  { key : '25426', value : 'MACHETA (CUNDINAMARCA)'},
  { key : '25430', value : 'MADRID (CUNDINAMARCA)'},
  { key : '25436', value : 'MANTA (CUNDINAMARCA)'},
  { key : '25438', value : 'MEDINA (CUNDINAMARCA)'},
  { key : '25473', value : 'MOSQUERA (CUNDINAMARCA)'},
  { key : '25483', value : 'NARIÑO (CUNDINAMARCA)'},
  { key : '25486', value : 'NEMOCON (CUNDINAMARCA)'},
  { key : '25488', value : 'NILO (CUNDINAMARCA)'},
  { key : '25489', value : 'NIMAIMA (CUNDINAMARCA)'},
  { key : '25491', value : 'NOCAIMA (CUNDINAMARCA)'},
  { key : '25506', value : 'VENECIA (CUNDINAMARCA)'},
  { key : '25513', value : 'PACHO (CUNDINAMARCA)'},
  { key : '25518', value : 'PAIME (CUNDINAMARCA)'},
  { key : '25524', value : 'PANDI (CUNDINAMARCA)'},
  { key : '25530', value : 'PARATEBUENO (CUNDINAMARCA)'},
  { key : '25535', value : 'PASCA (CUNDINAMARCA)'},
  { key : '25572', value : 'PUERTO SALGAR (CUNDINAMARCA)'},
  { key : '25580', value : 'PULI (CUNDINAMARCA)'},
  { key : '25592', value : 'QUEBRADANEGRA (CUNDINAMARCA)'},
  { key : '25594', value : 'QUETAME (CUNDINAMARCA)'},
  { key : '25596', value : 'QUIPILE (CUNDINAMARCA)'},
  { key : '25599', value : 'APULO (CUNDINAMARCA)'},
  { key : '25612', value : 'RICAURTE (CUNDINAMARCA)'},
  { key : '25645', value : 'SAN ANTONIO DEL TEQUENDAMA (CUNDINAMARCA)'},
  { key : '25649', value : 'SAN BERNARDO (CUNDINAMARCA)'},
  { key : '25653', value : 'SAN CAYETANO (CUNDINAMARCA)'},
  { key : '25658', value : 'SAN FRANCISCO (CUNDINAMARCA)'},
  { key : '25662', value : 'SAN JUAN DE RIO SECO (CUNDINAMARCA)'},
  { key : '25718', value : 'SASAIMA (CUNDINAMARCA)'},
  { key : '25736', value : 'SESQUILE (CUNDINAMARCA)'},
  { key : '25740', value : 'SIBATE (CUNDINAMARCA)'},
  { key : '25743', value : 'SILVANIA (CUNDINAMARCA)'},
  { key : '25745', value : 'SIMIJACA (CUNDINAMARCA)'},
  { key : '25754', value : 'SOACHA (CUNDINAMARCA)'},
  { key : '25758', value : 'SOPO (CUNDINAMARCA)'},
  { key : '25769', value : 'SUBACHOQUE (CUNDINAMARCA)'},
  { key : '25772', value : 'SUESCA (CUNDINAMARCA)'},
  { key : '25777', value : 'SUPATA (CUNDINAMARCA)'},
  { key : '25779', value : 'SUSA (CUNDINAMARCA)'},
  { key : '25781', value : 'SUTATAUSA (CUNDINAMARCA)'},
  { key : '25785', value : 'TABIO (CUNDINAMARCA)'},
  { key : '25793', value : 'TAUSA (CUNDINAMARCA)'},
  { key : '25797', value : 'TENA (CUNDINAMARCA)'},
  { key : '25799', value : 'TENJO (CUNDINAMARCA)'},
  { key : '25805', value : 'TIBACUY (CUNDINAMARCA)'},
  { key : '25807', value : 'TIBIRITA (CUNDINAMARCA)'},
  { key : '25815', value : 'TOCAIMA (CUNDINAMARCA)'},
  { key : '25817', value : 'TOCANCIPA (CUNDINAMARCA)'},
  { key : '25823', value : 'TOPAIPI (CUNDINAMARCA)'},
  { key : '25839', value : 'UBALA (CUNDINAMARCA)'},
  { key : '25841', value : 'UBAQUE (CUNDINAMARCA)'},
  { key : '25843', value : 'VILLA DE SAN DIEGO DE UBATE (CUNDINAMARCA)'},
  { key : '25845', value : 'UNE (CUNDINAMARCA)'},
  { key : '25851', value : 'UTICA (CUNDINAMARCA)'},
  { key : '25862', value : 'VERGARA (CUNDINAMARCA)'},
  { key : '25867', value : 'VIANI (CUNDINAMARCA)'},
  { key : '25871', value : 'VILLAGOMEZ (CUNDINAMARCA)'},
  { key : '25873', value : 'VILLAPINZON (CUNDINAMARCA)'},
  { key : '25875', value : 'VILLETA (CUNDINAMARCA)'},
  { key : '25878', value : 'VIOTA (CUNDINAMARCA)'},
  { key : '25885', value : 'YACOPI (CUNDINAMARCA)'},
  { key : '25898', value : 'ZIPACON (CUNDINAMARCA)'},
  { key : '25899', value : 'ZIPAQUIRA (CUNDINAMARCA)'},
  { key : '27001', value : 'QUIBDO (CHOCO)'},
  { key : '27006', value : 'ACANDI (CHOCO)'},
  { key : '27025', value : 'ALTO BAUDO (CHOCO)'},
  { key : '27050', value : 'ATRATO (CHOCO)'},
  { key : '27073', value : 'BAGADO (CHOCO)'},
  { key : '27075', value : 'BAHIA SOLANO (CHOCO)'},
  { key : '27077', value : 'BAJO BAUDO (CHOCO)'},
  { key : '27099', value : 'BOJAYA (CHOCO)'},
  { key : '27135', value : 'EL CANTON DEL SAN PABLO (CHOCO)'},
  { key : '27150', value : 'CARMEN DEL DARIEN (CHOCO)'},
  { key : '27160', value : 'CERTEGUI (CHOCO)'},
  { key : '27205', value : 'CONDOTO (CHOCO)'},
  { key : '27245', value : 'EL CARMEN DE ATRATO (CHOCO)'},
  { key : '27250', value : 'EL LITORAL DEL SAN JUAN (CHOCO)'},
  { key : '27361', value : 'ISTMINA (CHOCO)'},
  { key : '27372', value : 'JURADO (CHOCO)'},
  { key : '27413', value : 'LLORO (CHOCO)'},
  { key : '27425', value : 'MEDIO ATRATO (CHOCO)'},
  { key : '27430', value : 'MEDIO BAUDO (CHOCO)'},
  { key : '27450', value : 'MEDIO SAN JUAN (CHOCO)'},
  { key : '27491', value : 'NOVITA (CHOCO)'},
  { key : '27495', value : 'NUQUI (CHOCO)'},
  { key : '27580', value : 'RIO IRO (CHOCO)'},
  { key : '27600', value : 'RIO QUITO (CHOCO)'},
  { key : '27615', value : 'RIOSUCIO (CHOCO)'},
  { key : '27660', value : 'SAN JOSE DEL PALMAR (CHOCO)'},
  { key : '27745', value : 'SIPI (CHOCO)'},
  { key : '27787', value : 'TADO (CHOCO)'},
  { key : '27800', value : 'UNGUIA (CHOCO)'},
  { key : '27810', value : 'UNION PANAMERICANA (CHOCO)'},
  { key : '41001', value : 'NEIVA (HUILA)'},
  { key : '41006', value : 'ACEVEDO (HUILA)'},
  { key : '41013', value : 'AGRADO (HUILA)'},
  { key : '41016', value : 'AIPE (HUILA)'},
  { key : '41020', value : 'ALGECIRAS (HUILA)'},
  { key : '41026', value : 'ALTAMIRA (HUILA)'},
  { key : '41078', value : 'BARAYA (HUILA)'},
  { key : '41132', value : 'CAMPOALEGRE (HUILA)'},
  { key : '41206', value : 'COLOMBIA (HUILA)'},
  { key : '41244', value : 'ELIAS (HUILA)'},
  { key : '41298', value : 'GARZON (HUILA)'},
  { key : '41306', value : 'GIGANTE (HUILA)'},
  { key : '41319', value : 'GUADALUPE (HUILA)'},
  { key : '41349', value : 'HOBO (HUILA)'},
  { key : '41357', value : 'IQUIRA (HUILA)'},
  { key : '41359', value : 'ISNOS (HUILA)'},
  { key : '41378', value : 'LA ARGENTINA (HUILA)'},
  { key : '41396', value : 'LA PLATA (HUILA)'},
  { key : '41483', value : 'NATAGA (HUILA)'},
  { key : '41503', value : 'OPORAPA (HUILA)'},
  { key : '41518', value : 'PAICOL (HUILA)'},
  { key : '41524', value : 'PALERMO (HUILA)'},
  { key : '41530', value : 'PALESTINA (HUILA)'},
  { key : '41548', value : 'PITAL (HUILA)'},
  { key : '41551', value : 'PITALITO (HUILA)'},
  { key : '41615', value : 'RIVERA (HUILA)'},
  { key : '41660', value : 'SALADOBLANCO (HUILA)'},
  { key : '41668', value : 'SAN AGUSTIN (HUILA)'},
  { key : '41676', value : 'SANTA MARIA (HUILA)'},
  { key : '41770', value : 'SUAZA (HUILA)'},
  { key : '41791', value : 'TARQUI (HUILA)'},
  { key : '41797', value : 'TESALIA (HUILA)'},
  { key : '41799', value : 'TELLO (HUILA)'},
  { key : '41801', value : 'TERUEL (HUILA)'},
  { key : '41807', value : 'TIMANA (HUILA)'},
  { key : '41872', value : 'VILLAVIEJA (HUILA)'},
  { key : '41885', value : 'YAGUARA (HUILA)'},
  { key : '44001', value : 'RIOHACHA (LA GUAJIRA)'},
  { key : '44035', value : 'ALBANIA (LA GUAJIRA)'},
  { key : '44078', value : 'BARRANCAS (LA GUAJIRA)'},
  { key : '44090', value : 'DIBULLA (LA GUAJIRA)'},
  { key : '44098', value : 'DISTRACCION (LA GUAJIRA)'},
  { key : '44110', value : 'EL MOLINO (LA GUAJIRA)'},
  { key : '44279', value : 'FONSECA (LA GUAJIRA)'},
  { key : '44378', value : 'HATONUEVO (LA GUAJIRA)'},
  { key : '44420', value : 'LA JAGUA DEL PILAR (LA GUAJIRA)'},
  { key : '44430', value : 'MAICAO (LA GUAJIRA)'},
  { key : '44560', value : 'MANAURE (LA GUAJIRA)'},
  { key : '44650', value : 'SAN JUAN DEL CESAR (LA GUAJIRA)'},
  { key : '44847', value : 'URIBIA (LA GUAJIRA)'},
  { key : '44855', value : 'URUMITA (LA GUAJIRA)'},
  { key : '44874', value : 'VILLANUEVA (LA GUAJIRA)'},
  { key : '47001', value : 'SANTA MARTA (MAGDALENA)'},
  { key : '47030', value : 'ALGARROBO (MAGDALENA)'},
  { key : '47053', value : 'ARACATACA (MAGDALENA)'},
  { key : '47058', value : 'ARIGUANI (MAGDALENA)'},
  { key : '47161', value : 'CERRO SAN ANTONIO (MAGDALENA)'},
  { key : '47170', value : 'CHIBOLO (MAGDALENA)'},
  { key : '47189', value : 'CIENAGA (MAGDALENA)'},
  { key : '47205', value : 'CONCORDIA (MAGDALENA)'},
  { key : '47245', value : 'EL BANCO (MAGDALENA)'},
  { key : '47258', value : 'EL PIÑON (MAGDALENA)'},
  { key : '47268', value : 'EL RETEN (MAGDALENA)'},
  { key : '47288', value : 'FUNDACION (MAGDALENA)'},
  { key : '47318', value : 'GUAMAL (MAGDALENA)'},
  { key : '47460', value : 'NUEVA GRANADA (MAGDALENA)'},
  { key : '47541', value : 'PEDRAZA (MAGDALENA)'},
  { key : '47545', value : 'PIJIÑO DEL CARMEN (MAGDALENA)'},
  { key : '47551', value : 'PIVIJAY (MAGDALENA)'},
  { key : '47555', value : 'PLATO (MAGDALENA)'},
  { key : '47570', value : 'PUEBLOVIEJO (MAGDALENA)'},
  { key : '47605', value : 'REMOLINO (MAGDALENA)'},
  { key : '47660', value : 'SABANAS DE SAN ANGEL (MAGDALENA)'},
  { key : '47675', value : 'SALAMINA (MAGDALENA)'},
  { key : '47692', value : 'SAN SEBASTIAN DE BUENAVISTA (MAGDALENA)'},
  { key : '47703', value : 'SAN ZENON (MAGDALENA)'},
  { key : '47707', value : 'SANTA ANA (MAGDALENA)'},
  { key : '47720', value : 'SANTA BARBARA DE PINTO (MAGDALENA)'},
  { key : '47745', value : 'SITIONUEVO (MAGDALENA)'},
  { key : '47798', value : 'TENERIFE (MAGDALENA)'},
  { key : '47960', value : 'ZAPAYAN (MAGDALENA)'},
  { key : '47980', value : 'ZONA BANANERA (MAGDALENA)'},
  { key : '50001', value : 'VILLAVICENCIO (META)'},
  { key : '50006', value : 'ACACIAS (META)'},
  { key : '50110', value : 'BARRANCA DE UPIA (META)'},
  { key : '50124', value : 'CABUYARO (META)'},
  { key : '50150', value : 'CASTILLA LA NUEVA (META)'},
  { key : '50223', value : 'CUBARRAL (META)'},
  { key : '50226', value : 'CUMARAL (META)'},
  { key : '50245', value : 'EL CALVARIO (META)'},
  { key : '50251', value : 'EL CASTILLO (META)'},
  { key : '50270', value : 'EL DORADO (META)'},
  { key : '50287', value : 'FUENTE DE ORO (META)'},
  { key : '50313', value : 'GRANADA (META)'},
  { key : '50318', value : 'GUAMAL (META)'},
  { key : '50325', value : 'MAPIRIPAN (META)'},
  { key : '50330', value : 'MESETAS (META)'},
  { key : '50350', value : 'LA MACARENA (META)'},
  { key : '50370', value : 'URIBE (META)'},
  { key : '50400', value : 'LEJANIAS (META)'},
  { key : '50450', value : 'PUERTO CONCORDIA (META)'},
  { key : '50568', value : 'PUERTO GAITAN (META)'},
  { key : '50573', value : 'PUERTO LOPEZ (META)'},
  { key : '50577', value : 'PUERTO LLERAS (META)'},
  { key : '50590', value : 'PUERTO RICO (META)'},
  { key : '50606', value : 'RESTREPO (META)'},
  { key : '50680', value : 'SAN CARLOS DE GUAROA (META)'},
  { key : '50683', value : 'SAN JUAN DE ARAMA (META)'},
  { key : '50686', value : 'SAN JUANITO (META)'},
  { key : '50689', value : 'SAN MARTIN (META)'},
  { key : '50711', value : 'VISTAHERMOSA (META)'},
  { key : '52001', value : 'PASTO (NARIÑO)'},
  { key : '52019', value : 'ALBAN (NARIÑO)'},
  { key : '52022', value : 'ALDANA (NARIÑO)'},
  { key : '52036', value : 'ANCUYA (NARIÑO)'},
  { key : '52051', value : 'ARBOLEDA (NARIÑO)'},
  { key : '52079', value : 'BARBACOAS (NARIÑO)'},
  { key : '52083', value : 'BELEN (NARIÑO)'},
  { key : '52110', value : 'BUESACO (NARIÑO)'},
  { key : '52203', value : 'COLON (NARIÑO)'},
  { key : '52207', value : 'CONSACA (NARIÑO)'},
  { key : '52210', value : 'CONTADERO (NARIÑO)'},
  { key : '52215', value : 'CORDOBA (NARIÑO)'},
  { key : '52224', value : 'CUASPUD (NARIÑO)'},
  { key : '52227', value : 'CUMBAL (NARIÑO)'},
  { key : '52233', value : 'CUMBITARA (NARIÑO)'},
  { key : '52240', value : 'CHACHAGsI (NARIÑO)'},
  { key : '52250', value : 'EL CHARCO (NARIÑO)'},
  { key : '52254', value : 'EL PEÑOL (NARIÑO)'},
  { key : '52256', value : 'EL ROSARIO (NARIÑO)'},
  { key : '52258', value : 'EL TABLON DE GOMEZ (NARIÑO)'},
  { key : '52260', value : 'EL TAMBO (NARIÑO)'},
  { key : '52287', value : 'FUNES (NARIÑO)'},
  { key : '52317', value : 'GUACHUCAL (NARIÑO)'},
  { key : '52320', value : 'GUAITARILLA (NARIÑO)'},
  { key : '52323', value : 'GUALMATAN (NARIÑO)'},
  { key : '52352', value : 'ILES (NARIÑO)'},
  { key : '52354', value : 'IMUES (NARIÑO)'},
  { key : '52356', value : 'IPIALES (NARIÑO)'},
  { key : '52378', value : 'LA CRUZ (NARIÑO)'},
  { key : '52381', value : 'LA FLORIDA (NARIÑO)'},
  { key : '52385', value : 'LA LLANADA (NARIÑO)'},
  { key : '52390', value : 'LA TOLA (NARIÑO)'},
  { key : '52399', value : 'LA UNION (NARIÑO)'},
  { key : '52405', value : 'LEIVA (NARIÑO)'},
  { key : '52411', value : 'LINARES (NARIÑO)'},
  { key : '52418', value : 'LOS ANDES (NARIÑO)'},
  { key : '52427', value : 'MAGsI (NARIÑO)'},
  { key : '52435', value : 'MALLAMA (NARIÑO)'},
  { key : '52473', value : 'MOSQUERA (NARIÑO)'},
  { key : '52480', value : 'NARIÑO (NARIÑO)'},
  { key : '52490', value : 'OLAYA HERRERA (NARIÑO)'},
  { key : '52506', value : 'OSPINA (NARIÑO)'},
  { key : '52520', value : 'FRANCISCO PIZARRO (NARIÑO)'},
  { key : '52540', value : 'POLICARPA (NARIÑO)'},
  { key : '52560', value : 'POTOSI (NARIÑO)'},
  { key : '52565', value : 'PROVIDENCIA (NARIÑO)'},
  { key : '52573', value : 'PUERRES (NARIÑO)'},
  { key : '52585', value : 'PUPIALES (NARIÑO)'},
  { key : '52612', value : 'RICAURTE (NARIÑO)'},
  { key : '52621', value : 'ROBERTO PAYAN (NARIÑO)'},
  { key : '52678', value : 'SAMANIEGO (NARIÑO)'},
  { key : '52683', value : 'SANDONA (NARIÑO)'},
  { key : '52685', value : 'SAN BERNARDO (NARIÑO)'},
  { key : '52687', value : 'SAN LORENZO (NARIÑO)'},
  { key : '52693', value : 'SAN PABLO (NARIÑO)'},
  { key : '52694', value : 'SAN PEDRO DE CARTAGO (NARIÑO)'},
  { key : '52696', value : 'SANTA BARBARA (NARIÑO)'},
  { key : '52699', value : 'SANTACRUZ (NARIÑO)'},
  { key : '52720', value : 'SAPUYES (NARIÑO)'},
  { key : '52786', value : 'TAMINANGO (NARIÑO)'},
  { key : '52788', value : 'TANGUA (NARIÑO)'},
  { key : '52835', value : 'SAN ANDRES DE TUMACO (NARIÑO)'},
  { key : '52838', value : 'TUQUERRES (NARIÑO)'},
  { key : '52885', value : 'YACUANQUER (NARIÑO)'},
  { key : '54001', value : 'CUCUTA (N. DE SANTANDER)'},
  { key : '54003', value : 'ABREGO (N. DE SANTANDER)'},
  { key : '54051', value : 'ARBOLEDAS (N. DE SANTANDER)'},
  { key : '54099', value : 'BOCHALEMA (N. DE SANTANDER)'},
  { key : '54109', value : 'BUCARASICA (N. DE SANTANDER)'},
  { key : '54125', value : 'CACOTA (N. DE SANTANDER)'},
  { key : '54128', value : 'CACHIRA (N. DE SANTANDER)'},
  { key : '54172', value : 'CHINACOTA (N. DE SANTANDER)'},
  { key : '54174', value : 'CHITAGA (N. DE SANTANDER)'},
  { key : '54206', value : 'CONVENCION (N. DE SANTANDER)'},
  { key : '54223', value : 'CUCUTILLA (N. DE SANTANDER)'},
  { key : '54239', value : 'DURANIA (N. DE SANTANDER)'},
  { key : '54245', value : 'EL CARMEN (N. DE SANTANDER)'},
  { key : '54250', value : 'EL TARRA (N. DE SANTANDER)'},
  { key : '54261', value : 'EL ZULIA (N. DE SANTANDER)'},
  { key : '54313', value : 'GRAMALOTE (N. DE SANTANDER)'},
  { key : '54344', value : 'HACARI (N. DE SANTANDER)'},
  { key : '54347', value : 'HERRAN (N. DE SANTANDER)'},
  { key : '54377', value : 'LABATECA (N. DE SANTANDER)'},
  { key : '54385', value : 'LA ESPERANZA (N. DE SANTANDER)'},
  { key : '54398', value : 'LA PLAYA (N. DE SANTANDER)'},
  { key : '54405', value : 'LOS PATIOS (N. DE SANTANDER)'},
  { key : '54418', value : 'LOURDES (N. DE SANTANDER)'},
  { key : '54480', value : 'MUTISCUA (N. DE SANTANDER)'},
  { key : '54498', value : 'OCAÑA (N. DE SANTANDER)'},
  { key : '54518', value : 'PAMPLONA (N. DE SANTANDER)'},
  { key : '54520', value : 'PAMPLONITA (N. DE SANTANDER)'},
  { key : '54553', value : 'PUERTO SANTANDER (N. DE SANTANDER)'},
  { key : '54599', value : 'RAGONVALIA (N. DE SANTANDER)'},
  { key : '54660', value : 'SALAZAR (N. DE SANTANDER)'},
  { key : '54670', value : 'SAN CALIXTO (N. DE SANTANDER)'},
  { key : '54673', value : 'SAN CAYETANO (N. DE SANTANDER)'},
  { key : '54680', value : 'SANTIAGO (N. DE SANTANDER)'},
  { key : '54720', value : 'SARDINATA (N. DE SANTANDER)'},
  { key : '54743', value : 'SILOS (N. DE SANTANDER)'},
  { key : '54800', value : 'TEORAMA (N. DE SANTANDER)'},
  { key : '54810', value : 'TIBU (N. DE SANTANDER)'},
  { key : '54820', value : 'TOLEDO (N. DE SANTANDER)'},
  { key : '54871', value : 'VILLA CARO (N. DE SANTANDER)'},
  { key : '54874', value : 'VILLA DEL ROSARIO (N. DE SANTANDER)'},
  { key : '63001', value : 'ARMENIA (QUINDIO)'},
  { key : '63111', value : 'BUENAVISTA (QUINDIO)'},
  { key : '63130', value : 'CALARCA (QUINDIO)'},
  { key : '63190', value : 'CIRCASIA (QUINDIO)'},
  { key : '63212', value : 'CORDOBA (QUINDIO)'},
  { key : '63272', value : 'FILANDIA (QUINDIO)'},
  { key : '63302', value : 'GENOVA (QUINDIO)'},
  { key : '63401', value : 'LA TEBAIDA (QUINDIO)'},
  { key : '63470', value : 'MONTENEGRO (QUINDIO)'},
  { key : '63548', value : 'PIJAO (QUINDIO)'},
  { key : '63594', value : 'QUIMBAYA (QUINDIO)'},
  { key : '63690', value : 'SALENTO (QUINDIO)'},
  { key : '66001', value : 'PEREIRA (RISARALDA)'},
  { key : '66045', value : 'APIA (RISARALDA)'},
  { key : '66075', value : 'BALBOA (RISARALDA)'},
  { key : '66088', value : 'BELEN DE UMBRIA (RISARALDA)'},
  { key : '66170', value : 'DOSQUEBRADAS (RISARALDA)'},
  { key : '66318', value : 'GUATICA (RISARALDA)'},
  { key : '66383', value : 'LA CELIA (RISARALDA)'},
  { key : '66400', value : 'LA VIRGINIA (RISARALDA)'},
  { key : '66440', value : 'MARSELLA (RISARALDA)'},
  { key : '66456', value : 'MISTRATO (RISARALDA)'},
  { key : '66572', value : 'PUEBLO RICO (RISARALDA)'},
  { key : '66594', value : 'QUINCHIA (RISARALDA)'},
  { key : '66682', value : 'SANTA ROSA DE CABAL (RISARALDA)'},
  { key : '66687', value : 'SANTUARIO (RISARALDA)'},
  { key : '68001', value : 'BUCARAMANGA (SANTANDER)'},
  { key : '68013', value : 'AGUADA (SANTANDER)'},
  { key : '68020', value : 'ALBANIA (SANTANDER)'},
  { key : '68051', value : 'ARATOCA (SANTANDER)'},
  { key : '68077', value : 'BARBOSA (SANTANDER)'},
  { key : '68079', value : 'BARICHARA (SANTANDER)'},
  { key : '68081', value : 'BARRANCABERMEJA (SANTANDER)'},
  { key : '68092', value : 'BETULIA (SANTANDER)'},
  { key : '68101', value : 'BOLIVAR (SANTANDER)'},
  { key : '68121', value : 'CABRERA (SANTANDER)'},
  { key : '68132', value : 'CALIFORNIA (SANTANDER)'},
  { key : '68147', value : 'CAPITANEJO (SANTANDER)'},
  { key : '68152', value : 'CARCASI (SANTANDER)'},
  { key : '68160', value : 'CEPITA (SANTANDER)'},
  { key : '68162', value : 'CERRITO (SANTANDER)'},
  { key : '68167', value : 'CHARALA (SANTANDER)'},
  { key : '68169', value : 'CHARTA (SANTANDER)'},
  { key : '68176', value : 'CHIMA (SANTANDER)'},
  { key : '68179', value : 'CHIPATA (SANTANDER)'},
  { key : '68190', value : 'CIMITARRA (SANTANDER)'},
  { key : '68207', value : 'CONCEPCION (SANTANDER)'},
  { key : '68209', value : 'CONFINES (SANTANDER)'},
  { key : '68211', value : 'CONTRATACION (SANTANDER)'},
  { key : '68217', value : 'COROMORO (SANTANDER)'},
  { key : '68229', value : 'CURITI (SANTANDER)'},
  { key : '68235', value : 'EL CARMEN DE CHUCURI (SANTANDER)'},
  { key : '68245', value : 'EL GUACAMAYO (SANTANDER)'},
  { key : '68250', value : 'EL PEÑON (SANTANDER)'},
  { key : '68255', value : 'EL PLAYON (SANTANDER)'},
  { key : '68264', value : 'ENCINO (SANTANDER)'},
  { key : '68266', value : 'ENCISO (SANTANDER)'},
  { key : '68271', value : 'FLORIAN (SANTANDER)'},
  { key : '68276', value : 'FLORIDABLANCA (SANTANDER)'},
  { key : '68296', value : 'GALAN (SANTANDER)'},
  { key : '68298', value : 'GAMBITA (SANTANDER)'},
  { key : '68307', value : 'GIRON (SANTANDER)'},
  { key : '68318', value : 'GUACA (SANTANDER)'},
  { key : '68320', value : 'GUADALUPE (SANTANDER)'},
  { key : '68322', value : 'GUAPOTA (SANTANDER)'},
  { key : '68324', value : 'GUAVATA (SANTANDER)'},
  { key : '68327', value : 'GsEPSA (SANTANDER)'},
  { key : '68344', value : 'HATO (SANTANDER)'},
  { key : '68368', value : 'JESUS MARIA (SANTANDER)'},
  { key : '68370', value : 'JORDAN (SANTANDER)'},
  { key : '68377', value : 'LA BELLEZA (SANTANDER)'},
  { key : '68385', value : 'LANDAZURI (SANTANDER)'},
  { key : '68397', value : 'LA PAZ (SANTANDER)'},
  { key : '68406', value : 'LEBRIJA (SANTANDER)'},
  { key : '68418', value : 'LOS SANTOS (SANTANDER)'},
  { key : '68425', value : 'MACARAVITA (SANTANDER)'},
  { key : '68432', value : 'MALAGA (SANTANDER)'},
  { key : '68444', value : 'MATANZA (SANTANDER)'},
  { key : '68464', value : 'MOGOTES (SANTANDER)'},
  { key : '68468', value : 'MOLAGAVITA (SANTANDER)'},
  { key : '68498', value : 'OCAMONTE (SANTANDER)'},
  { key : '68500', value : 'OIBA (SANTANDER)'},
  { key : '68502', value : 'ONZAGA (SANTANDER)'},
  { key : '68522', value : 'PALMAR (SANTANDER)'},
  { key : '68524', value : 'PALMAS DEL SOCORRO (SANTANDER)'},
  { key : '68533', value : 'PARAMO (SANTANDER)'},
  { key : '68547', value : 'PIEDECUESTA (SANTANDER)'},
  { key : '68549', value : 'PINCHOTE (SANTANDER)'},
  { key : '68572', value : 'PUENTE NACIONAL (SANTANDER)'},
  { key : '68573', value : 'PUERTO PARRA (SANTANDER)'},
  { key : '68575', value : 'PUERTO WILCHES (SANTANDER)'},
  { key : '68615', value : 'RIONEGRO (SANTANDER)'},
  { key : '68655', value : 'SABANA DE TORRES (SANTANDER)'},
  { key : '68669', value : 'SAN ANDRES (SANTANDER)'},
  { key : '68673', value : 'SAN BENITO (SANTANDER)'},
  { key : '68679', value : 'SAN GIL (SANTANDER)'},
  { key : '68682', value : 'SAN JOAQUIN (SANTANDER)'},
  { key : '68684', value : 'SAN JOSE DE MIRANDA (SANTANDER)'},
  { key : '68686', value : 'SAN MIGUEL (SANTANDER)'},
  { key : '68689', value : 'SAN VICENTE DE CHUCURI (SANTANDER)'},
  { key : '68705', value : 'SANTA BARBARA (SANTANDER)'},
  { key : '68720', value : 'SANTA HELENA DEL OPON (SANTANDER)'},
  { key : '68745', value : 'SIMACOTA (SANTANDER)'},
  { key : '68755', value : 'SOCORRO (SANTANDER)'},
  { key : '68770', value : 'SUAITA (SANTANDER)'},
  { key : '68773', value : 'SUCRE (SANTANDER)'},
  { key : '68780', value : 'SURATA (SANTANDER)'},
  { key : '68820', value : 'TONA (SANTANDER)'},
  { key : '68855', value : 'VALLE DE SAN JOSE (SANTANDER)'},
  { key : '68861', value : 'VELEZ (SANTANDER)'},
  { key : '68867', value : 'VETAS (SANTANDER)'},
  { key : '68872', value : 'VILLANUEVA (SANTANDER)'},
  { key : '68895', value : 'ZAPATOCA (SANTANDER)'},
  { key : '70001', value : 'SINCELEJO (SUCRE)'},
  { key : '70110', value : 'BUENAVISTA (SUCRE)'},
  { key : '70124', value : 'CAIMITO (SUCRE)'},
  { key : '70204', value : 'COLOSO (SUCRE)'},
  { key : '70215', value : 'COROZAL (SUCRE)'},
  { key : '70221', value : 'COVEÑAS (SUCRE)'},
  { key : '70230', value : 'CHALAN (SUCRE)'},
  { key : '70233', value : 'EL ROBLE (SUCRE)'},
  { key : '70235', value : 'GALERAS (SUCRE)'},
  { key : '70265', value : 'GUARANDA (SUCRE)'},
  { key : '70400', value : 'LA UNION (SUCRE)'},
  { key : '70418', value : 'LOS PALMITOS (SUCRE)'},
  { key : '70429', value : 'MAJAGUAL (SUCRE)'},
  { key : '70473', value : 'MORROA (SUCRE)'},
  { key : '70508', value : 'OVEJAS (SUCRE)'},
  { key : '70523', value : 'PALMITO (SUCRE)'},
  { key : '70670', value : 'SAMPUES (SUCRE)'},
  { key : '70678', value : 'SAN BENITO ABAD (SUCRE)'},
  { key : '70702', value : 'SAN JUAN DE BETULIA (SUCRE)'},
  { key : '70708', value : 'SAN MARCOS (SUCRE)'},
  { key : '70713', value : 'SAN ONOFRE (SUCRE)'},
  { key : '70717', value : 'SAN PEDRO (SUCRE)'},
  { key : '70742', value : 'SAN LUIS DE SINCE (SUCRE)'},
  { key : '70771', value : 'SUCRE (SUCRE)'},
  { key : '70820', value : 'SANTIAGO DE TOLU (SUCRE)'},
  { key : '70823', value : 'TOLU VIEJO (SUCRE)'},
  { key : '73001', value : 'IBAGUE (TOLIMA)'},
  { key : '73024', value : 'ALPUJARRA (TOLIMA)'},
  { key : '73026', value : 'ALVARADO (TOLIMA)'},
  { key : '73030', value : 'AMBALEMA (TOLIMA)'},
  { key : '73043', value : 'ANZOATEGUI (TOLIMA)'},
  { key : '73055', value : 'ARMERO (TOLIMA)'},
  { key : '73067', value : 'ATACO (TOLIMA)'},
  { key : '73124', value : 'CAJAMARCA (TOLIMA)'},
  { key : '73148', value : 'CARMEN DE APICALA (TOLIMA)'},
  { key : '73152', value : 'CASABIANCA (TOLIMA)'},
  { key : '73168', value : 'CHAPARRAL (TOLIMA)'},
  { key : '73200', value : 'COELLO (TOLIMA)'},
  { key : '73217', value : 'COYAIMA (TOLIMA)'},
  { key : '73226', value : 'CUNDAY (TOLIMA)'},
  { key : '73236', value : 'DOLORES (TOLIMA)'},
  { key : '73268', value : 'ESPINAL (TOLIMA)'},
  { key : '73270', value : 'FALAN (TOLIMA)'},
  { key : '73275', value : 'FLANDES (TOLIMA)'},
  { key : '73283', value : 'FRESNO (TOLIMA)'},
  { key : '73319', value : 'GUAMO (TOLIMA)'},
  { key : '73347', value : 'HERVEO (TOLIMA)'},
  { key : '73349', value : 'HONDA (TOLIMA)'},
  { key : '73352', value : 'ICONONZO (TOLIMA)'},
  { key : '73408', value : 'LERIDA (TOLIMA)'},
  { key : '73411', value : 'LIBANO (TOLIMA)'},
  { key : '73443', value : 'MARIQUITA (TOLIMA)'},
  { key : '73449', value : 'MELGAR (TOLIMA)'},
  { key : '73461', value : 'MURILLO (TOLIMA)'},
  { key : '73483', value : 'NATAGAIMA (TOLIMA)'},
  { key : '73504', value : 'ORTEGA (TOLIMA)'},
  { key : '73520', value : 'PALOCABILDO (TOLIMA)'},
  { key : '73547', value : 'PIEDRAS (TOLIMA)'},
  { key : '73555', value : 'PLANADAS (TOLIMA)'},
  { key : '73563', value : 'PRADO (TOLIMA)'},
  { key : '73585', value : 'PURIFICACION (TOLIMA)'},
  { key : '73616', value : 'RIOBLANCO (TOLIMA)'},
  { key : '73622', value : 'RONCESVALLES (TOLIMA)'},
  { key : '73624', value : 'ROVIRA (TOLIMA)'},
  { key : '73671', value : 'SALDAÑA (TOLIMA)'},
  { key : '73675', value : 'SAN ANTONIO (TOLIMA)'},
  { key : '73678', value : 'SAN LUIS (TOLIMA)'},
  { key : '73686', value : 'SANTA ISABEL (TOLIMA)'},
  { key : '73770', value : 'SUAREZ (TOLIMA)'},
  { key : '73854', value : 'VALLE DE SAN JUAN (TOLIMA)'},
  { key : '73861', value : 'VENADILLO (TOLIMA)'},
  { key : '73870', value : 'VILLAHERMOSA (TOLIMA)'},
  { key : '73873', value : 'VILLARRICA (TOLIMA)'},
  { key : '76001', value : 'CALI (VALLE DEL CAUCA)'},
  { key : '76020', value : 'ALCALA (VALLE DEL CAUCA)'},
  { key : '76036', value : 'ANDALUCIA (VALLE DEL CAUCA)'},
  { key : '76041', value : 'ANSERMANUEVO (VALLE DEL CAUCA)'},
  { key : '76054', value : 'ARGELIA (VALLE DEL CAUCA)'},
  { key : '76100', value : 'BOLIVAR (VALLE DEL CAUCA)'},
  { key : '76109', value : 'BUENAVENTURA (VALLE DEL CAUCA)'},
  { key : '76111', value : 'GUADALAJARA DE BUGA (VALLE DEL CAUCA)'},
  { key : '76113', value : 'BUGALAGRANDE (VALLE DEL CAUCA)'},
  { key : '76122', value : 'CAICEDONIA (VALLE DEL CAUCA)'},
  { key : '76126', value : 'CALIMA (VALLE DEL CAUCA)'},
  { key : '76130', value : 'CANDELARIA (VALLE DEL CAUCA)'},
  { key : '76147', value : 'CARTAGO (VALLE DEL CAUCA)'},
  { key : '76233', value : 'DAGUA (VALLE DEL CAUCA)'},
  { key : '76243', value : 'EL AGUILA (VALLE DEL CAUCA)'},
  { key : '76246', value : 'EL CAIRO (VALLE DEL CAUCA)'},
  { key : '76248', value : 'EL CERRITO (VALLE DEL CAUCA)'},
  { key : '76250', value : 'EL DOVIO (VALLE DEL CAUCA)'},
  { key : '76275', value : 'FLORIDA (VALLE DEL CAUCA)'},
  { key : '76306', value : 'GINEBRA (VALLE DEL CAUCA)'},
  { key : '76318', value : 'GUACARI (VALLE DEL CAUCA)'},
  { key : '76364', value : 'JAMUNDI (VALLE DEL CAUCA)'},
  { key : '76377', value : 'LA CUMBRE (VALLE DEL CAUCA)'},
  { key : '76400', value : 'LA UNION (VALLE DEL CAUCA)'},
  { key : '76403', value : 'LA VICTORIA (VALLE DEL CAUCA)'},
  { key : '76497', value : 'OBANDO (VALLE DEL CAUCA)'},
  { key : '76520', value : 'PALMIRA (VALLE DEL CAUCA)'},
  { key : '76563', value : 'PRADERA (VALLE DEL CAUCA)'},
  { key : '76606', value : 'RESTREPO (VALLE DEL CAUCA)'},
  { key : '76616', value : 'RIOFRIO (VALLE DEL CAUCA)'},
  { key : '76622', value : 'ROLDANILLO (VALLE DEL CAUCA)'},
  { key : '76670', value : 'SAN PEDRO (VALLE DEL CAUCA)'},
  { key : '76736', value : 'SEVILLA (VALLE DEL CAUCA)'},
  { key : '76823', value : 'TORO (VALLE DEL CAUCA)'},
  { key : '76828', value : 'TRUJILLO (VALLE DEL CAUCA)'},
  { key : '76834', value : 'TULUA (VALLE DEL CAUCA)'},
  { key : '76845', value : 'ULLOA (VALLE DEL CAUCA)'},
  { key : '76863', value : 'VERSALLES (VALLE DEL CAUCA)'},
  { key : '76869', value : 'VIJES (VALLE DEL CAUCA)'},
  { key : '76890', value : 'YOTOCO (VALLE DEL CAUCA)'},
  { key : '76892', value : 'YUMBO (VALLE DEL CAUCA)'},
  { key : '76895', value : 'ZARZAL (VALLE DEL CAUCA)'},
  { key : '81001', value : 'ARAUCA (ARAUCA)'},
  { key : '81065', value : 'ARAUQUITA (ARAUCA)'},
  { key : '81220', value : 'CRAVO NORTE (ARAUCA)'},
  { key : '81300', value : 'FORTUL (ARAUCA)'},
  { key : '81591', value : 'PUERTO RONDON (ARAUCA)'},
  { key : '81736', value : 'SARAVENA (ARAUCA)'},
  { key : '81794', value : 'TAME (ARAUCA)'},
  { key : '85001', value : 'YOPAL (CASANARE)'},
  { key : '85010', value : 'AGUAZUL (CASANARE)'},
  { key : '85015', value : 'CHAMEZA (CASANARE)'},
  { key : '85125', value : 'HATO COROZAL (CASANARE)'},
  { key : '85136', value : 'LA SALINA (CASANARE)'},
  { key : '85139', value : 'MANI (CASANARE)'},
  { key : '85162', value : 'MONTERREY (CASANARE)'},
  { key : '85225', value : 'NUNCHIA (CASANARE)'},
  { key : '85230', value : 'OROCUE (CASANARE)'},
  { key : '85250', value : 'PAZ DE ARIPORO (CASANARE)'},
  { key : '85263', value : 'PORE (CASANARE)'},
  { key : '85279', value : 'RECETOR (CASANARE)'},
  { key : '85300', value : 'SABANALARGA (CASANARE)'},
  { key : '85315', value : 'SACAMA (CASANARE)'},
  { key : '85325', value : 'SAN LUIS DE PALENQUE (CASANARE)'},
  { key : '85400', value : 'TAMARA (CASANARE)'},
  { key : '85410', value : 'TAURAMENA (CASANARE)'},
  { key : '85430', value : 'TRINIDAD (CASANARE)'},
  { key : '85440', value : 'VILLANUEVA (CASANARE)'},
  { key : '86001', value : 'MOCOA (PUTUMAYO)'},
  { key : '86219', value : 'COLON (PUTUMAYO)'},
  { key : '86320', value : 'ORITO (PUTUMAYO)'},
  { key : '86568', value : 'PUERTO ASIS (PUTUMAYO)'},
  { key : '86569', value : 'PUERTO CAICEDO (PUTUMAYO)'},
  { key : '86571', value : 'PUERTO GUZMAN (PUTUMAYO)'},
  { key : '86573', value : 'LEGUIZAMO (PUTUMAYO)'},
  { key : '86749', value : 'SIBUNDOY (PUTUMAYO)'},
  { key : '86755', value : 'SAN FRANCISCO (PUTUMAYO)'},
  { key : '86757', value : 'SAN MIGUEL (PUTUMAYO)'},
  { key : '86760', value : 'SANTIAGO (PUTUMAYO)'},
  { key : '86865', value : 'VALLE DEL GUAMUEZ (PUTUMAYO)'},
  { key : '86885', value : 'VILLAGARZON (PUTUMAYO)'},
  { key : '88001', value : 'SAN ANDRES (SAN ANDRES)'},
  { key : '88564', value : 'PROVIDENCIA (SAN ANDRES)'},
  { key : '91001', value : 'LETICIA (AMAZONAS)'},
  { key : '91263', value : 'EL ENCANTO (AMAZONAS)'},
  { key : '91405', value : 'LA CHORRERA (AMAZONAS)'},
  { key : '91407', value : 'LA PEDRERA (AMAZONAS)'},
  { key : '91430', value : 'LA VICTORIA (AMAZONAS)'},
  { key : '91460', value : 'MIRITI - PARANA (AMAZONAS)'},
  { key : '91530', value : 'PUERTO ALEGRIA (AMAZONAS)'},
  { key : '91536', value : 'PUERTO ARICA (AMAZONAS)'},
  { key : '91540', value : 'PUERTO NARIÑO (AMAZONAS)'},
  { key : '91669', value : 'PUERTO SANTANDER (AMAZONAS)'},
  { key : '91798', value : 'TARAPACA (AMAZONAS)'},
  { key : '94001', value : 'INIRIDA (GUAINIA)'},
  { key : '94343', value : 'BARRANCO MINAS (GUAINIA)'},
  { key : '94663', value : 'MAPIRIPANA (GUAINIA)'},
  { key : '94883', value : 'SAN FELIPE (GUAINIA)'},
  { key : '94884', value : 'PUERTO COLOMBIA (GUAINIA)'},
  { key : '94885', value : 'LA GUADALUPE (GUAINIA)'},
  { key : '94886', value : 'CACAHUAL (GUAINIA)'},
  { key : '94887', value : 'PANA PANA (GUAINIA)'},
  { key : '94888', value : 'MORICHAL (GUAINIA)'},
  { key : '95001', value : 'SAN JOSE DEL GUAVIARE (GUAVIARE)'},
  { key : '95015', value : 'CALAMAR (GUAVIARE)'},
  { key : '95025', value : 'EL RETORNO (GUAVIARE)'},
  { key : '95200', value : 'MIRAFLORES (GUAVIARE)'},
  { key : '97001', value : 'MITU (VAUPES)'},
  { key : '97161', value : 'CARURU (VAUPES)'},
  { key : '97511', value : 'PACOA (VAUPES)'},
  { key : '97666', value : 'TARAIRA (VAUPES)'},
  { key : '97777', value : 'PAPUNAUA (VAUPES)'},
  { key : '97889', value : 'YAVARATE (VAUPES)'},
  { key : '99001', value : 'PUERTO CARREÑO (VICHADA)'},
  { key : '99524', value : 'LA PRIMAVERA (VICHADA)'},
  { key : '99624', value : 'SANTA ROSALIA (VICHADA)'},
  { key : '99773', value : 'CUMARIBO (VICHADA)'}];
  
  EPSList : Array<KeyValue> = [{ key : '1', value : 'AMBUQ' },
  { key : '2', value : 'CAJACOPI' },
  { key : '3', value : 'COMFACOR' },
  { key : '4', value : 'COMFASUCRE' },
  { key : '5', value : 'COMPARTA' },
  { key : '6', value : 'COOSALUD' },
  { key : '7', value : 'EMDISALUD' },
  { key : '8', value : 'MUTUAL SER' },
  { key : '9', value : 'NUEVA EPS SUBSIDIADA' },
  { key : '10', value : 'SALUDVIDA' },
  { key : '11', value : 'CAFESALUD' },
  { key : '12', value : 'COOMEVA' },
  { key : '13', value : 'NUEVA EPS CONTRIBUTIVO' },
  { key : '14', value : 'SALUD TOTAL' },
  { key : '15', value : 'EPS SANITAS' }];


  constructor() { }

  ngOnInit() {
  }

}
